[General]
# Path to the wallpaper. If it's in the assets folder, use "assets/background.jpg"
background=assets/background.jpg

# Material You-like colors
primaryColor={{color4}}
accentColor={{color4}}
autoColor=false
use24HourClock=true
backgroundColor={{color0}}
textColor={{foreground}}

# Font settings
fontFamily=Ubuntu
fontSize=14
