#!/usr/bin/env python3
"""
generate-hyprtoolkit.py
Génère ~/.config/hypr/hyprtoolkit.conf depuis le JSON hex de matugen.
Usage: echo "$MATUGEN_JSON" | python3 generate-hyprtoolkit.py
"""

import json
import sys
import os

OUTPUT = os.path.expanduser("~/.config/hypr/hyprtoolkit.conf")

def hex_to_hypr(color: str) -> str:
    """Convertit #RRGGBB → 0xFFRRGGBB"""
    c = color.lstrip("#")
    return f"0xFF{c.upper()}"

def get_color(data: dict, *keys: str, fallback: str = "#303030") -> str:
    try:
        node = data
        for k in keys:
            node = node[k]
        return node
    except (KeyError, TypeError):
        return fallback

def main():
    raw = sys.stdin.read().strip()
    if not raw:
        print("generate-hyprtoolkit: stdin vide, abandon.", file=sys.stderr)
        sys.exit(1)

    # Le JSON peut contenir plusieurs objets collés (matugen bug connu) — on prend le premier
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        # Tente de parser uniquement le premier objet JSON
        depth = 0
        end = 0
        for i, ch in enumerate(raw):
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break
        try:
            data = json.loads(raw[:end])
        except json.JSONDecodeError as e:
            print(f"generate-hyprtoolkit: JSON invalide — {e}", file=sys.stderr)
            sys.exit(1)

    c = data.get("colors", {})

    bg           = hex_to_hypr(get_color(c, "background",             "default", "color", fallback="#181818"))
    base         = hex_to_hypr(get_color(c, "surface_container",      "default", "color", fallback="#202020"))
    alt_base     = hex_to_hypr(get_color(c, "surface_container_high", "default", "color", fallback="#272727"))
    text         = hex_to_hypr(get_color(c, "on_surface",             "default", "color", fallback="#dadada"))
    bright_text  = hex_to_hypr(get_color(c, "on_background",          "default", "color", fallback="#ffdede"))
    accent       = hex_to_hypr(get_color(c, "primary",                "default", "color", fallback="#00ffcc"))
    accent_sec   = hex_to_hypr(get_color(c, "secondary",              "default", "color", fallback="#0099f0"))

    conf = f"""\
# Auto-generated by matugen via generate-hyprtoolkit.py
# DO NOT EDIT MANUALLY — regenerated on each wallpaper change

general {{
    # Colors (0xAARRGGBB)
    background       = {bg}
    base             = {base}
    alternate_base   = {alt_base}
    text             = {text}
    bright_text      = {bright_text}
    accent           = {accent}
    accent_secondary = {accent_sec}

    # Typography
    font_family           = Sans Serif
    font_family_monospace = monospace
    font_size             = 11
    h1_size               = 19
    h2_size               = 15
    h3_size               = 13
    small_font_size       = 10

    # Rounding
    rounding_large = 12
    rounding_small = 6
}}
"""

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write(conf)

    print(f"generate-hyprtoolkit: écrit → {OUTPUT}")

if __name__ == "__main__":
    main()
