# $hyprDir = $HOME/.config/hypr
$mpris_art = /tmp/hyde-mpris.png
$wall = $HOME/.config/hypr/hyprlock/wallpapers/6.png

# BACKGROUND
background {
    monitor =
    path = $HOME/.cache/current-wallpaper
    blur_passes = 4
    blur_size = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    disable_loading_bar = false
    grace = 1
}

# GREETINGS
label {
    monitor =
    text =Welcome!
    color = $text
    font_size = 55
    font_family = JetBrainsMono Nerd Font
    position = -630, 320
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = $text
    font_size = 40
    font_family = JetBrainsMono Nerd Font
    position = -630, 240
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = Sunday, September 29
    color = $text
    font_size = 20
    text_align = left
    font_family = JetBrainsMono Nerd Font
    position = 180, 175
    halign = left
    valign = center
}

# Profie-Photo
image {
    monitor =
    path = $HOME/.config/hypr/hyprlock/wallpapers/user.jpg
    border_size = 1
    border_color = $accent
    size = 160
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd =
    position = -630, 25
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = $bg
    rounding = -1
    border_size = 0
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = -630, -140
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =  $USER
    color = $text
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position =-630, -140
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = $accent
    font_color = $text
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i><span foreground="##bac2de">🔒 Enter Pass</span></i>
    hide_input = false
    position = -630, -220
    halign = center
    valign = center
}

# Dragons be here - music widget

# Music blur div
shape {
    monitor =
    size = 350, 110
    color = $bg
    rounding = 20
    rotate = 0
    position = -630, -350
    halign = center
    valign = center
    zindex = 1
}

# Music Album Art
image {
    monitor =
    path = $mpris_art
    size = 86
	border_size = 3
    border_color = $accent
    rounding = 5
    rotate = 0
    reload_time = 0
    reload_cmd =
    position = 167, -350
    halign = left
    valign = center
    zindex = 5
}


# PLAYER ARTIST
label {
    monitor =
    text = cmd[update:1000] echo "$($music --artist)"
    color = $text
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 270, -375
    halign = left
    valign = center
    zindex = 5
}

# PLAYER TITLE
label {
    monitor =
    text = cmd[update:1000] echo "$($music --title)"
    color = $text
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 270, -350
    halign = left
    valign = center
    zindex = 5
}

# PLAYER SOURCE
label {
    monitor =
    text = cmd[update:1000] echo "$($music --source)" &
    color = $text
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono
    position = 270, -320
    halign = left
    valign = center
    zindex = 5
}
