[General]
# Path to the wallpaper. If it's in the assets folder, use "assets/background.jpg"
background=assets/background.jpg

# Material You-like colors
primaryColor={{colors.primary.default.hex}}
accentColor={{colors.tertiary.default.hex}}
autoColor=false
use24HourClock=true
backgroundColor={{colors.surface.default.hex}}
textColor={{colors.on_surface.default.hex}}

# Font settings
fontFamily=Ubuntu
fontSize=14
